import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import RedirectButton from '@/components/RedirectButton';
import LogoTwo from '@/components/LogoTwo';

export default function Home() {
  const onFormSubmit = (e) => {
    e.preventDefault();
  };

  return (
    <div className="h-screen min:h-96 max:h-full   ">
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* container box */}

      <div class="h-screen  bg-white items-center  px-4 py-6 flex flex-col animate__animated animate__fadeIn   sm:py-12">
        <div className="relative py-3 sm:max-w-xl mx-auto text-center">
          {/* Logo or tittle */}
          <div className="flex gap-6 justify-center flex-col items-center  ">
            <LogoTwo />
            <a class="text-4xl font-medium  text-[#13131C] yasc">Sign In</a>
          </div>

          <div class="relative mt-4  bg-white  sm:rounde-lg text-left ">
            {/* Form */}
            <div class="h-2 bg-white  rounded-t-md top-1 relative"></div>
            <form class="py-6 px-8  bg-white  rounded-md   ">
              <label class="block font-medium text-[#13131C]">Email</label>
              <input
                type="text"
                placeholder="user@email.com"
                class="bg-white placeholder:text-left  text-[#13131C] border-b-2  focus:outline-none w-72 h-5 py-5 mt-2     "
              />
              <label class="block mt-3 font-medium text-[#13131C]">
                Password
              </label>
              <input
                minlength="8"
                required
                type="password"
                placeholder="Password"
                class="  bg-white   h-5  border-b-2 py-5 mt-2 focus:outline-none w-72  focus:ring-paleblue "
              />
              <div class="flex justify-center items-baseline">
                <RedirectButton />
                {/* loading animation  */}

                {/* <button
                  onSubmit={onFormSubmit}
                  type="submit"
                  onClick={(e) => {
                    e.preventDefault();
                    window.location.href = '/Home';
                  }}
                  class="mt-4 bg-paleblue text-lavander py-2 px-6 shadow rounded-full hover:bg-blue active:bg-[#50506A]"
                >
                  Login
                </button> */}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
